### ISSUE TITLE
infinite loading issue after completion of lesson 

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#832]
**Steps to reproduce**
1. play any lesson
2. click on continue in popup

**Logs:**
```
CocosGame.tsx:200 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')
    at CocosGame.tsx:200:35
    at f (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
(anonymous)	@	CocosGame.tsx:200
```

**Comment by Ashish1998** [comment]
Fixed
